### ISSUE TITLE
Eval exception with high version of Microsoft.CodeAnalysis.* references installed

### ISSUE THREAD

**Issue by zhzhwcn** [bruce-dunwiddie/data-eval#27]
Test code 

    string ex = @"return ""Test"";";
    var evaluator = new Evaluator(ex);
    var r3 = evaluator.Eval();

throws

    System.MissingMethodException:“Method not found: 'Void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, Boolean, System.String, System.String, System.String, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String, System.Collections.Immutable.ImmutableArray`1<Byte>, System.Nullable`1<Boolean>, Microsoft.CodeAnalysis.Platform, Microsoft.CodeAnalysis.ReportDiagnostic, Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>>, Boolean, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider, Boolean, Microsoft.CodeAnalysis.MetadataImportOptions, Microsoft.CodeAnalysis.CSharp.NullableContextOptions)'.”

Stack 

    at Data.Eval.Compilation.Compiler.Compile(String classText, List`1 referenceAssemblies)
    at Data.Eval.Evaluator.InitEval(String caller)
    at Data.Eval.Evaluator.EvalInternal(String caller)
    at Data.Eval.Evaluator.EvalInternal()
    at Data.Eval.Evaluator.Eval()
    at ConsoleApp3.Program.Main(String[] args) in ConsoleApp3\Program.cs:line 13

With Nuget version 2.4.4 and flowing refrences
    
    Microsoft.CodeAnalysis 3.6.0
    Microsoft.CodeAnalysis.Common 3.6.0
    Microsoft.CodeAnalysis.CSharp 3.6.0
    Microsoft.CodeAnalysis.CSharp.Workspaces 3.6.0
    Microsoft.CodeAnalysis.Workspaces.Common 3.6.0

**Comment by zhzhwcn** [comment]
If i download the DataEval source code and upgrade the DataEval refrences and use it, every thine works fine

**Comment by bruce-dunwiddie** [comment]
Thank you for reporting this issue.

Can you please tell me which .Net environment you were compiling the application against when pulling in the Nuget? (e.g. .Net Framework or .Net Core, and which version)

Also, can you tell me what Operating System version you're compiling on?

The dependencies definition of the package seem to already contain the packages I would think contain those definitions, but maybe I will need to also explicitly add the inner dependencies.

Dependencies:
Microsoft.CodeAnalysis (>= 3.2.1)
Microsoft.CodeAnalysis.CSharp (>= 3.2.1)
System.Collections.Immutable (>= 1.5.0)

**Comment by bruce-dunwiddie** [comment]
Reading into this a bit more, if I were to try to recreate, you're saying that your base application already had Microsoft.CodeAnalysis references added, but quite a few versions higher than the requirement, e.g. 3.6.0. Then you got the package from Nuget, and that appears to have created a misalignment of references, possibly between Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.Csharp?

I'm going to see if I can hopefully recreate.

**Comment by zhzhwcn** [comment]
> Reading into this a bit more, if I were to try to recreate, you're saying that your base application already had Microsoft.CodeAnalysis references added, but quite a few versions higher than the requirement, e.g. 3.6.0. Then you got the package from Nuget, and that appears to have created a misalignment of references, possibly between Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.Csharp?
> 
> I'm going to see if I can hopefully recreate.

Yes

**Comment by bruce-dunwiddie** [comment]
I was able to recreate the issue, but it appeared to be a binary incompatibility issue that could only be solved by bindings within the application or a bunch of nasty reflection, so I went ahead and just upgraded the dependencies within the package and published a new version. This cleared the issue in my recreation scenario. https://www.nuget.org/packages/Data.Eval/2.4.5
